### ISSUE TITLE
Current block lags

### ISSUE THREAD

**Issue by frankisawesome** [blockchain-etl/blockchain-etl-streaming#14]
<img width="1238" alt="Screen Shot 2020-08-05 at 11 23 37 am" src="https://user-images.githubusercontent.com/39414003/89361307-542d7280-d70e-11ea-8c31-a79daf5e86a7.png">

Current block is not being updated on the 10 seconds interval?

**Comment by medvedev1088** [comment]
It looks like the node is stuck on block 10573538 for some time. Most likely there is a syncing issue with the node.

**Comment by frankisawesome** [comment]
spot on man, thanks for that.
